version: '3.8'
services:
  api-pdfgenerator-nest:
    container_name: api-pdfgenerator-nest
    # image: docker-image:tag
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: on-failure
    ports:
      - '3003:3003'
    volumes:
      - ./src:/app/src
      - ./logs:/app/logs
      - ./templates:/app/templates
    networks:
      - net-pdfgenerator-nest
      - net-eli-kafka

  db-pdfgenerator-nest:
    image: postgres:16-alpine
    container_name: db-pdfgenerator-nest
    restart: on-failure
    ports:
      - '5431:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: db
    networks:
      - net-pdfgenerator-nest
      - net-eli-kafka

networks:
  net-pdfgenerator-nest:
    name: net-pdfgenerator-nest
    external: false
  net-eli-kafka:
    name: net-eli-kafka
    external: true
